# fly.toml app configuration file generated for fullstack-pokedex-jslindgit-126 on 2023-06-06T17:06:27+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fullstack-pokedex-jslindgit-126"
primary_region = "arn"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "5000"

[deploy]
  release_command = "npm run buildtempfail"

[build]
  [build.args]
    NODE_VERSION = "16.20.0"

[processes]
  app = "node app.js"

[experimental]
  auto_rollback = true	

[[services]]
  internal_port = 5000
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "15s"
    interval = "30s"
    restart_limit = 0
    timeout = "10s"

  [[services.http_checks]]
    interval = 10000
    grace_period = "15s"
    method = "get"
    path = "/health"
    protocol = "http"
    restart_limit = 0
    timeout = 5000
    tls_skip_verify = false
    [services.http_checks.headers]

  [[services.script_checks]]
    command="./health_check_2.sh"
    grace_period = "15s"
    interval = "30s"
    restart_limit = 0
    timeout = "10s"