# fly.toml app configuration file generated for fullstack-pokedex-jslindgit-126 on 2023-06-06T17:06:27+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fullstack-pokedex-jslindgit-126"
primary_region = "arn"

[env]
  PORT = "5000"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

